### ISSUE TITLE
status: "NOT_AUTHENTICATED" everytime i'm trying to login

### ISSUE THREAD

**Issue by novasite** [elaniin/AccountKit-Web-PHP#1]
After i'm entering sms code popup window is closing and in callback receive in response object `Object {status: "NOT_AUTHENTICATED"}`.

```
function accountKitLoginCallback(response){
    console.log(response);
}
function accountKitEmailLogin(){
    AccountKit.login(
        'EMAIL',
        {},
        accountKitLoginCallback
    );
}
function accountKitPhoneLogin(){
    AccountKit.login(
        'PHONE',
        {},
        accountKitLoginCallback
    );
}

AccountKit_OnInteractive = function(){
    AccountKit.init(
        {
            appId: xxx,
            state: csrftoken,
            version:"v1.0"
        }
    );
};
```
How can i debug it and figure out the reason?

**Comment by elaniin** [comment]
Hi,

We've tried your code with our App ID and CSRF and works perfect, we received on the response the "PARTIALLY_AUTHENTICATED" status to continue to the next step. Can you send us a screenshot of how you have configured you App/Account Kit, maybe there is the problem. Regards.
