### ISSUE TITLE
A system issue occured. Please try again.

### ISSUE THREAD

**Issue by devellopah** [elaniin/AccountKit-Web-PHP#12]
I am on linux mint, git cloned repo to _/var/www/html/accountkit_
it's correctly opens on **http://localhost/accountkit/**, but when i click login button(no matter which one), the dialog with error message pop up. 
Please help to figure the problem and how can i tackle it. Thanks in advance!
![accountkit_error](https://user-images.githubusercontent.com/13398931/60383958-0f51f980-9a81-11e9-9573-27066d6a4954.png)

**Comment by devellopah** [comment]
Why in you demo app, when i successfully login, i see session starts, but when reload page, i am again asked to login?

**Comment by elinares** [comment]
Hi!
You can improve the validation to verify if the session exists, right now in our code the validation is ignoring the session. We are working on it.
