### ISSUE TITLE
Uncaught TypeError: i.replace is not a function

### ISSUE THREAD

**Issue by durnezj** [elaniin/AccountKit-Web-PHP#3]
I get the following error when submitting the form after i have authenticated with sms or email:

Uncaught TypeError: i.replace is not a function

It is encountered in the facebook sdk Javascript and I do not know what caused this or how to fix it.
Maybe you can help or have encountered this?

**Comment by SnelleJelle** [comment]
mijn error: http://i.imgur.com/8qOfZag.png

**Comment by elaniin** [comment]
Hi @durnezj let me check right now.

**Comment by elaniin** [comment]
Hi,
We continue working to find the error, looks like the problem is in the Facebook JS SDK. But we will reply when we have the example working again.

**Comment by durnezj** [comment]
@elaniin Have you found a solution yet?

**Comment by saimoomsafayet** [comment]
Any solution??

**Comment by jirkahronik** [comment]
Hey everyone. I was troubled by this issue too and took some time to troubleshoot. It's just a missing second parameter in AccountKit.login() function call. 

Replace this code
`AccountKit.login('EMAIL', loginCallback);`
by
`AccountKit.login('EMAIL', **{}**, loginCallback);`

And see magic happen :)

**Comment by elaniin** [comment]
@jirkahronik Thank You! Works perfect now.

**Comment by barakataliforoz** [comment]
for me still it is not working.
Note: I am clicking the login with sms button on page load with javascript.
 same error displaying.

**Comment by tansah** [comment]
Hi.. I know this thread is closed, but now a year plus later, Im still finding the same issue with account kit. I learn that the extra {} part is actually forwarding default value to the email address text box, yet no matter what combination i tried, (omitting {}, leaving {}, adding {emailAddress:'something'}) i still receive the same error message after the popped up window dialog closed after succesfull confirmation.

Help please.. I hope im only missing out on something..

**Comment by barakataliforoz** [comment]
@tansah You can store and email address to a variable and pass it in the function. For example:
    var email_address = document.getElementById("email").value;
or var email_address = youremail@yourdomain.com;
then. It is working for me and should work for you as well.
    AccountKit.login('EMAIL', {emailAddress: email_address}, loginCallback);

**Comment by elinares** [comment]
@tansah can we see your code or you have the error message that is showed to you? in this way we can see how to help you because our demo site is working: http://toolboxsv.com/dev/accountkit_php/

**Comment by tansah** [comment]
Thanks @elinares & @barakataliforoz, really appreciate. Its quite a long code.. 

To be honest i am only starting to try out this facebook feature, i feel that im missing something very simple & straightforward.. just that i dont know where i got it wrong.

I manage to see everything on the popup window until past the rounded check animation finished, showing "Account verified" with continue button, and when clicking that continue button, the popup window closed, and you have that error message.

SMS login works perfectly fine.

The url of the webpage is at https://www.tansah.com/instant-website/
Attached below the php code (token etc removed)
[temp.php.zip](https://github.com/elaniin/AccountKit-Web-PHP/files/1499838/temp.php.zip)

**Comment by webmaniabr** [comment]
Has anyone found a solution to this problem?

**Comment by tansah** [comment]
I also created a quick screencast, explaining how it happened.
[fb screencast.mpeg.zip](https://github.com/elaniin/AccountKit-Web-PHP/files/1503623/fb.screencast.mpeg.zip)

any help would be appreciated

**Comment by webmaniabr** [comment]
@tansah Exactly, is the same error. I'm in touch with Facebook support and the correction has already been started. As soon as they correct I update here as well.

**Comment by tansah** [comment]
@webmaniabr Thanks so much webmaniabr, really appreciate. Will be rooting & staying tune here.

**Comment by webmaniabr** [comment]
Hey guys, this problem have been fixed by facebook support. In my tests it worked like a charm.
