### ISSUE TITLE
 AccountKit.login is not a function

### ISSUE THREAD

**Issue by barakataliforoz** [elaniin/AccountKit-Web-PHP#5]
I am trying to skip clicking the button "login with sms", because i am sending the parameters from another page. so i want to directly go to popup.
Note: I am clicking the login with sms button on page load with javascript.
 error: 

> TypeError: AccountKit.login is not a function

**Comment by trilleplay** [comment]
Error on your end. Not in this projects scope.

**Comment by barakataliforoz** [comment]
Thank you for your reply. The issue was with the browser because it was blocking the pop up  when I was running it with programming script.
